CREATE TABLE nationals_hitting_2021 (
	GAME_ID SERIAL,
	PLAYER_NAME VARCHAR(255) NOT NULL,
	POSITION VARCHAR(10) NOT NULL,
	AB INT NOT NULL,
	R INT NOT NULL,
	H INT NOT NULL,
	RBI INT NOT NULL,
	BB INT NOT NULL,
	K INT NOT NULL,
	PA INT NOT NULL,
	_2B INT NOT NULL,
	_3B INT NOT NULL,
	HR INT NOT NULL,
	TB INT NOT NULL,
	HBP INT NOT NULL,
	Pit INT NOT NULL,
	Str INT NOT NULL
);