DROP TABLE IF EXISTS league_team_pitch_stats;

CREATE TABLE league_team_pitch_stats (
    "year" int  NOT NULL,
	"teamID" varchar(3) NOT NULL,
	"numPitchers" int NOT NULL,
	"pitcherAvgAge" float NOT NULL,
	"runsAllowedPerGame" float NOT NULL,
	"wins" int NOT NULL ,
	"losses" int NOT NULL ,
	"winlosspercentage" float NOT NULL,
	"era" float NOT NULL,
	"gamesPlayed" int NOT NULL,
	"gamesStarted" int NOT NULL,
	"gamesFinished" int NOT NULL,
	"completegames" int NOT NULL,
	"teamShutout" int NOT NULL,
	"completeShutout" int NOT NULL,
	"saves" int NOT NULL,
	"innPitch" float NOT NULL,
	"oppHits" int NOT NULL,
	"oppRuns" int NOT NULL,
	"oppEarnRuns" int NOT NULL,
	"oppHomeRuns" int NOT NULL,
	"oppBB" int NOT NULL,
	"oppIBB" int NOT NULL,
	"pStrikeouts" int NOT NULL,
	"oppHBP" int NOT NULL,
	"balks" int NOT NULL,
	"wildPitches" int NOT NULL,
	"battersFaced" int NOT NULL,
	"era+" float NOT NULL,
	"fip" float NOT NULL,
	"whip" float NOT NULL,
	"hitsPer9" float NOT NULL,
	"homeRunsPer9" float NOT NULL,
	"baseOnBallsPer9" float NOT NULL,
	"strikeoutsPer9" float NOT NULL,
	"strikeoutsPerWin" float NOT NULL,
	"runnersLeftOnBase" int NOT NULL,
    CONSTRAINT "pk_league_pitching_stats" PRIMARY KEY (
        "year","teamID"
     )
);